# R Packages

This chapter lists all the packages necessary for plotting

## Data processing

```{r}
library(tidyverse)
```

## Data packages

```{r}
#install_github("thiyangt/elephants")
library(elephants)
```

## Large dataset

```{r}
data("elephants")
```

### Glimpse of the large dataset

```{r,echo=FALSE, message=FALSE, warning=FALSE,fig.width=20, fig.height=20}
GGally::ggpairs(elephants, aes(col=Gender)) +   scale_color_manual(values=c("male"="#d95f02","female"="#1b9e77")) + 
  scale_fill_manual(values=c("male"="#d95f02","female"="#1b9e77"))
```

## Small dataset

```{r}
set.seed(2023)
elephants.subset.100 <- elephants |> sample_n(100)
```

### Glimpse of the small dataset

```{r,echo=FALSE, message=FALSE, warning=FALSE,fig.width=20, fig.height=20}
GGally::ggpairs(elephants.subset.100, aes(col=Category)) + scale_color_manual(values=c("male"="#d95f02","female"="#1b9e77")) + 
  scale_fill_manual(values=c("male"="#d95f02","female"="#1b9e77"))
```



## Packages related to geom

```{r}
library(ggplot2)
#devtools::install_github("EvaMaeRey/ggxmean")
#library(gxmean)
#devtools::install_github("davidsjoberg/ggsankey")
library(ggxmean)
```

## geom Extensions

```{r}
library(GGally) # Matrix plots
```

## All available geom_... in the ggplot2 package

```{r, echo=FALSE}
ls(pattern = '^geom_', env = as.environment('package:ggplot2')) |> knitr::kable()
```