# D: geom_d...


## geom_delaunay_tile

**Description:** The Delaunay triangulation is used to create a planar graph.



```{r, eval=FALSE}
worldbankdata |>
  filter(Year==2021) |>
 ggplot(aes(y = Cooking, x = Electricity)) +
  ggforce::geom_delaunay_tile(alpha = 0.5, colour = 'black') + labs(title="geom_delaunay_tile") + theme(aspect.ratio = 1)
```


```{r}
# to compare with geom_point
point <- ggplot(worldbankdata, aes(y = Cooking, x= Electricity)) +
  geom_point(alpha = 0.5, colour = 'black') + labs(title="geom_point") + theme(aspect.ratio = 1)

library(patchwork)
delaunay|point
```



## geom_density


```{r}
worldbankdata |>
  filter(Year == 2021) |>
ggplot(aes(x = Cooking)) + 
  geom_density()

```

## geom_density_2d

```{r}
worldbankdata |>
  filter(Year == 2021) |>
ggplot(aes(y = Cooking, x=Electricity)) + 
  geom_density_2d()

```

## geom_density_2d_filled

```{r}
worldbankdata |>
  filter(Year == 2021) |>
ggplot(aes(y = Cooking, x=Electricity))  + 
  geom_density_2d_filled()

```



## geom_density_ridges

Here the `y` variable should be qualitative and the `x` variable should be quantitative.


```{r}
library(ggridges)
worldbankdata |>
  filter(Year == 2021) |>
ggplot(aes(y = Income, x=Cooking))  + 
    geom_density_ridges()

```

## geom_dl

```{r}
library(directlabels)
worldbankdata |>
  filter(Year == 2021) |>
ggplot(aes(y = Cooking, x=Electricity, col=Income)) + 
  geom_point() +
  geom_dl(aes(label=Income),method="smart.grid")
```