# V: geom_v...

## geom_vline{#vline}


**Package: ** ggplot2 [@R-ggplot2]

**Book: **

**Description: ** Draw a vertical line ($X=c$) for a given value of $c$, which is known as `xintercept`.

**Understandable aesthetics:** alpha, colour, linetype, linewidth

**Statistics layer(s):**

**See also: ** [geom_point](#point), , [geom_hline](#hline), [geom_smooth](#smooth), [geom_vline](#vline)

**Example:**

```{r, fig.cap="Illustration of (A) geom_vline and (B) use of geom_point and geom_vline both"}
vline <- ggplot(worldbankdata, aes(y = Cooking, xb= Electricity)) + geom_vline(xintercept = 50) + 
  labs(title="A: `geom_vline` only") +
  theme(aspect.ratio = 1)

pointvline <- vline + 
  geom_point() + 
  geom_vline(xintercept = 50) + 
  labs(title="B: `geom_point + geom_vline` both") +
  theme(aspect.ratio = 1)

library(patchwork)
vline | pointvline
```

## geom_violin

```{r, echo=FALSE}
worldbankdata |>
  filter(Year == 2021) |>
ggplot(aes(y = Cooking, x=Income)) + 
  geom_violin()

```

Without trimming

```{r, echo=FALSE}
worldbankdata |>
  filter(Year == 2021) |>
ggplot(aes(y = Cooking, x=Income)) +
  geom_violin(trim=FALSE)

```


Draw quantiles

```{r, echo=FALSE}
worldbankdata |>
  filter(Year == 2021) |>
ggplot(aes(y = Cooking, x=Income)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75))

```
