project:
  type: book
  output-dir: docs

book:
  title: "Data Visualisation <span style='color:red;'>Geom</span>etries Encyclopedia"
  subtitle: "Geoms in the Grammar of Graphics: All Types of Plots"
  author: "Thiyanga S. Talagala"
  downloads: [pdf, epub]
  reader-mode: true
  page-footer:
    left: |
      Data Visualisation Geometries Encyclopedia was written by Thiyanga S. Talagala.
    right: |
      GEOM Encyclopedia (Encyclopedia of Plots)
  site-url: https://thiyangt.github.io/geom.encyclopedia/
  repo-url: https://github.com/thiyangt/geom.encyclopedia
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - a.qmd
    - b.qmd
    - c.qmd
    - d.qmd
    - e.qmd
    - f.qmd
    - g.qmd
    - h.qmd
    - i.qmd
    - j.qmd
    - k.qmd
    - l.qmd
    - m.qmd
    - n.qmd
    - o.qmd
    - p.qmd
    - q.qmd  
    - r.qmd
    - s.qmd
    - t.qmd  
    - u.qmd
    - v.qmd  
    - w.qmd
    - x.qmd  
    - y.qmd 
    - z.qmd  
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



