# I  {#sec-i}

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(drone)
library(patchwork)
library(ggpattern)
data("worldbankdata")
```

## geom_image {#image}


**Package**

ggimage [@ggimage]

**Description**

Visualise data through images.

**Understandable aesthetics**

`image`


**See also**

[geom_emoji](#emoji)

**Example**

```{r, warning=FALSE, message=FALSE, fig.height=5, fig.width=5}
library("ggimage")
df <- data.frame(x = rnorm(10),
                 y = rnorm(10),
                image = sample("https://www.r-project.org/logo/Rlogo.png",
                              size=10, replace = TRUE))
ggplot(df, aes(x, y)) + geom_image(aes(image=image))
```


## geom_icon {#icon}

### Example

```{r, warning=FALSE, message=FALSE, fig.height=5, fig.width=5, eval=FALSE}
library("ggimage")
df <- data.frame(x = rnorm(10),
                 y = rnorm(10))
df$icon = sample(c('ios-power', 'ios-wifi', 'ios-pie'), 10, replace=TRUE)
ggplot(df, aes(x, y)) + geom_icon(aes(image=icon))
```

